/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacyproject;

import DB.DBConnection;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author COMPAQ
 */
public class MemberWindow extends javax.swing.JFrame {

    /**
     * Creates new form MemberWindow
     */
    String user;
    public MemberWindow() {
        initComponents();
    }
    public MemberWindow(String uname) {
        initComponents();
        user=uname;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Bill = new javax.swing.JInternalFrame();
        jPanel12 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        GnrtInvc = new javax.swing.JInternalFrame();
        jPanel11 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jTextField36 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jTextField41 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jTextField42 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        profile = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        chng_pass = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        billSearch = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        view_bill = new javax.swing.JInternalFrame();
        jPanel16 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalPharmacy/viewPro.png"))); // NOI18N
        jButton1.setToolTipText("View Profile");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalPharmacy/genInvc.jpg"))); // NOI18N
        jButton2.setToolTipText("Generate Invoice");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalPharmacy/viewInvc.png"))); // NOI18N
        jButton3.setToolTipText("View Invoice by Bill");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalPharmacy/chng.png"))); // NOI18N
        jButton4.setToolTipText("Change Password");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalPharmacy/logout.png"))); // NOI18N
        jButton5.setToolTipText("Sign Out");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jDesktopPane1.setBackground(new java.awt.Color(255, 204, 255));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bill.setClosable(true);
        Bill.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        Bill.setTitle("Bill");
        Bill.setVisible(false);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel60.setText("Invoice Number :");
        jPanel12.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 120, -1, -1));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel61.setText("Customer Name :");
        jPanel12.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 185, -1, -1));

        jLabel62.setText("jLabel62");
        jLabel62.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel12.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 120, 250, -1));

        jLabel63.setText("jLabel63");
        jLabel63.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel12.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 185, 250, -1));

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel64.setText("Invoice Date :");
        jPanel12.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 120, -1, -1));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel65.setText("Contact Number :");
        jPanel12.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 185, -1, -1));

        jLabel66.setText("jLabel66");
        jLabel66.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel12.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 120, 250, -1));

        jLabel67.setText("jLabel67");
        jLabel67.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel12.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 185, 250, -1));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 880, 230));

        jLabel68.setText("Invoice ");
        jPanel12.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel69.setText("SHDC Pharma");
        jPanel12.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        jLabel70.setText("Sita[ur , 5480934809");
        jPanel12.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, -1, -1));

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel71.setText("Amount to pay :");
        jPanel12.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, -1, -1));

        jLabel72.setText("jLabel72");
        jLabel72.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel12.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 250, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Total amount :");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel22.setText("jLabel22");
        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 250, -1));

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BillLayout = new javax.swing.GroupLayout(Bill.getContentPane());
        Bill.getContentPane().setLayout(BillLayout);
        BillLayout.setHorizontalGroup(
            BillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(75, 75, 75))
        );
        BillLayout.setVerticalGroup(
            BillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDesktopPane1.add(Bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 970, 530));

        GnrtInvc.setClosable(true);
        GnrtInvc.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        GnrtInvc.setTitle("Generate Invoice");
        GnrtInvc.setVisible(false);

        jPanel11.setBackground(new java.awt.Color(204, 204, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel51.setText("Generate Invoice ");
        jPanel11.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 11, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(255, 204, 204));
        jPanel11.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 46, 246, 10));

        jLabel52.setText("Medicine Name :");
        jPanel11.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 98, -1, -1));

        jLabel53.setText("Price :");
        jPanel11.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 169, -1, -1));

        jLabel54.setText("Mfd. Date :");
        jPanel11.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 238, -1, -1));

        jLabel55.setText("Exp. Date :");
        jPanel11.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 310, -1, -1));

        jLabel56.setText("Avl. Quantity :");
        jPanel11.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 387, -1, -1));

        jButton27.setBackground(new java.awt.Color(255, 255, 51));
        jButton27.setText("Add Cart");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        jButton28.setBackground(new java.awt.Color(51, 255, 51));
        jButton28.setText("Bill");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, -1, -1));

        jTextField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField36ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 166, 358, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel11.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 95, 358, -1));
        jPanel11.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 235, 358, -1));
        jPanel11.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 304, 358, -1));
        jPanel11.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 384, 358, -1));

        jPanel13.setBackground(new java.awt.Color(218, 206, 253));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Customer Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 22), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel58.setText("Customer Contact ");

        jLabel59.setText("Customer Name");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel59)
                            .addComponent(jLabel58)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField41)
                            .addComponent(jTextField42, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel59)
                .addGap(18, 18, 18)
                .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel58)
                .addGap(27, 27, 27)
                .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 340, 260));

        jLabel57.setText("Quantity :");
        jPanel11.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));
        jPanel11.add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 360, -1));

        javax.swing.GroupLayout GnrtInvcLayout = new javax.swing.GroupLayout(GnrtInvc.getContentPane());
        GnrtInvc.getContentPane().setLayout(GnrtInvcLayout);
        GnrtInvcLayout.setHorizontalGroup(
            GnrtInvcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GnrtInvcLayout.setVerticalGroup(
            GnrtInvcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(GnrtInvc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 980, 510));

        profile.setClosable(true);
        profile.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        profile.setTitle("Profile");
        profile.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setText("Code :");

        jLabel3.setText("Name :");

        jLabel4.setText("Post :");

        jLabel5.setText("DOB :");

        jLabel6.setText("Qualitfication :");

        jLabel7.setText("Gender :");

        jLabel8.setText("Address :");

        jLabel9.setText("Contact :");

        jLabel10.setText("Email :");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jTextField5.setText("jTextField5");

        jTextField6.setText("jTextField6");

        jTextField7.setText("jTextField7");

        jTextField8.setText("jTextField8");

        jTextField9.setText("jTextField9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jTextField7)
                    .addComponent(jTextField8))
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel10)
                .addGap(77, 77, 77)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout profileLayout = new javax.swing.GroupLayout(profile.getContentPane());
        profile.getContentPane().setLayout(profileLayout);
        profileLayout.setHorizontalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        profileLayout.setVerticalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 950, 470));

        chng_pass.setClosable(true);
        chng_pass.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        chng_pass.setTitle("Change Password");
        chng_pass.setVisible(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Change Password ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Old Password :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("New Password :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Confirm Password :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 20));

        jButton7.setBackground(new java.awt.Color(255, 255, 0));
        jButton7.setForeground(new java.awt.Color(51, 51, 255));
        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 330, -1));

        jPasswordField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 330, -1));

        jPasswordField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 330, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 250, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalPharmacy/OqH4GUk.jpg"))); // NOI18N
        jLabel11.setText("Change Password");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 400));

        javax.swing.GroupLayout chng_passLayout = new javax.swing.GroupLayout(chng_pass.getContentPane());
        chng_pass.getContentPane().setLayout(chng_passLayout);
        chng_passLayout.setHorizontalGroup(
            chng_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );
        chng_passLayout.setVerticalGroup(
            chng_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        jDesktopPane1.add(chng_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 680, 430));

        billSearch.setClosable(true);
        billSearch.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        billSearch.setTitle("Search Invoice By Bill Number");
        billSearch.setVisible(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Search Invoice By Bill Number ");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Enter Bill Number :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 360, -1));

        jButton8.setBackground(new java.awt.Color(255, 255, 0));
        jButton8.setForeground(new java.awt.Color(51, 51, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalPharmacy/Search.png"))); // NOI18N
        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 400, 10));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalPharmacy/changePass.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 240));

        javax.swing.GroupLayout billSearchLayout = new javax.swing.GroupLayout(billSearch.getContentPane());
        billSearch.getContentPane().setLayout(billSearchLayout);
        billSearchLayout.setHorizontalGroup(
            billSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        billSearchLayout.setVerticalGroup(
            billSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
        );

        jDesktopPane1.add(billSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 720, 270));

        view_bill.setClosable(true);
        view_bill.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        view_bill.setTitle("Bill");
        view_bill.setVisible(false);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel73.setText("Invoice Number :");
        jPanel16.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 120, -1, -1));

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel74.setText("Customer Name :");
        jPanel16.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 185, -1, -1));

        jLabel75.setText("jLabel62");
        jLabel75.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel16.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 120, 250, -1));

        jLabel76.setText("jLabel63");
        jLabel76.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel16.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 185, 250, -1));

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel77.setText("Invoice Date :");
        jPanel16.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 120, -1, -1));

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel78.setText("Contact Number :");
        jPanel16.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 185, -1, -1));

        jLabel79.setText("jLabel66");
        jLabel79.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel16.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 120, 250, -1));

        jLabel80.setText("jLabel67");
        jLabel80.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel16.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 185, 250, -1));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 880, 210));

        jLabel81.setText("Invoice ");
        jPanel16.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel82.setText("SHDC Pharma");
        jPanel16.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        jLabel83.setText("Sita[ur , 5480934809");
        jPanel16.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, -1, -1));

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel84.setText("Amount to pay :");
        jPanel16.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, -1, -1));

        jLabel85.setText("jLabel72");
        jLabel85.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel16.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 250, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("total amount to pay :");
        jPanel16.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel20.setText("jLabel20");
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel16.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 190, -1));

        jButton9.setText("Print");

        javax.swing.GroupLayout view_billLayout = new javax.swing.GroupLayout(view_bill.getContentPane());
        view_bill.getContentPane().setLayout(view_billLayout);
        view_billLayout.setHorizontalGroup(
            view_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_billLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(97, 97, 97))
        );
        view_billLayout.setVerticalGroup(
            view_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_billLayout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );

        jDesktopPane1.add(view_bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 980, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalPharmacy/master2 (1).jpg"))); // NOI18N
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1010, 540));

        jMenu1.setText("Profile");

        jMenuItem1.setText("View Profile");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Invoice");

        jMenuItem2.setText("Generate Invoice");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("View Invoice By Bill NO.");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Account");

        jMenuItem4.setText("Change Password");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Sign Out");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try{
            DBConnection db=new DBConnection();
            db.pstmt=db.con.prepareStatement("select * from emp_mstr where email=?");
            db.pstmt.setString(1,user);
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next()){
                jTextField1.setText(db.rst.getString(1));
                jTextField2.setText(db.rst.getString(2));
                jTextField3.setText(db.rst.getString(3));
                jTextField4.setText(db.rst.getString(4));
                jTextField5.setText(db.rst.getString(5));
                jTextField6.setText(db.rst.getString(6));
                jTextField7.setText(db.rst.getString(7));
                jTextField8.setText(db.rst.getString(8));
                jTextField9.setText(db.rst.getString(9));
            }
            profile.setVisible(true);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    int invc;
    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        int avl=Integer.parseInt(jTextField39.getText());
        int cqnt=Integer.parseInt(jTextField40.getText());
        if(avl>=cqnt){
            try{
                String mname=jComboBox3.getSelectedItem().toString();
                String pri=jTextField36.getText();
                String mqnt=jTextField40.getText();
                String cname=jTextField41.getText();
                String cust_cont=jTextField42.getText();
                
                String emp_id="";
                DBConnection db=new DBConnection();
                db.pstmt=db.con.prepareStatement("select * from emp_mstr where email=?");
                db.pstmt.setString(1,user);
                db.rst=db.pstmt.executeQuery();
                if(db.rst.next()){
                    emp_id=db.rst.getString(1);
                }
                db.pstmt=db.con.prepareStatement("INSERT INTO invoice(invoice_id,med_name,med_price,med_qty,invc_date_time,cust_name,cust_contact,emp_id) values (?,?,?,?,?,?,?,?)");
                db.pstmt.setInt(1,invc);
                db.pstmt.setString(2,mname);
                db.pstmt.setString(3,pri);
                db.pstmt.setString(4,mqnt);
                db.pstmt.setString(5,new java.util.Date().toString());
                db.pstmt.setString(6,cname);
                db.pstmt.setString(7,cust_cont);
                db.pstmt.setString(8,emp_id);
                int i1=db.pstmt.executeUpdate();
                db.pstmt=db.con.prepareStatement("update stock_detail set med_qty=? where med_name=?");
                db.pstmt.setInt(1,(avl-cqnt));
                db.pstmt.setString(2,mname);
                int i2=db.pstmt.executeUpdate();
                if(i1>0 && i2>0){
                    JOptionPane.showMessageDialog(this,"added in cart Successfully");
                    jTextField36.setText("");
                    jTextField37.setText("");
                    jTextField38.setText("");
                    jTextField39.setText("");
                    jTextField40.setText("");
                }
            }
            catch(Exception e){
                e.printStackTrace();

            }
        }
        else{
            JOptionPane.showMessageDialog(this,"can't add into cart");
            jTextField40.setText("");
        }
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        try{
            int amn=0,price,qnty;
            DBConnection db=new DBConnection();
            db.pstmt=db.con.prepareStatement("select med_price , med_qty from invoice where invoice_id=?");
            db.pstmt.setInt(1,invc);
            db.rst=db.pstmt.executeQuery();
            while(db.rst.next()){
                price=db.rst.getInt(1);
                qnty=db.rst.getInt(2);
                amn+=(price*qnty);
            }
            String cname=jTextField41.getText();
            String cust_cont=jTextField42.getText();
            db.pstmt=db.con.prepareStatement("insert into bill_detail values(?,?,?,?,?)");
            db.pstmt.setInt(1,invc);
            db.pstmt.setString(2,new Date().toString());
            db.pstmt.setString(3,cname);
            db.pstmt.setString(4,cust_cont);
            db.pstmt.setInt(5,amn);
            int i1=db.pstmt.executeUpdate();
            Vector<String> head=new Vector<String>();
            Vector<Vector<String>> data=new  Vector<Vector<String>>();
            head.add("Medicine name");
            head.add("Mfd. Date");
            head.add("Exp. Date");
            head.add("Price");
            head.add("Quantity");
            head.add("Amount");
            db.pstmt=db.con.prepareStatement("select invoice.med_name,stock_detail.med_mfd,stock_detail.med_exd,invoice.med_price,invoice.med_qty from invoice,stock_detail where invoice.med_name=stock_detail.med_name and invoice_id=?");
            db.pstmt.setInt(1,invc);
            db.rst=db.pstmt.executeQuery();
            while(db.rst.next()){
                Vector<String> tem=new Vector<String>();
                tem.add(db.rst.getString(1));
                tem.add(db.rst.getString(2));
                tem.add(db.rst.getString(3));
                tem.add(db.rst.getString(4));
                tem.add(db.rst.getString(5));
                int amt1=Integer.parseInt(db.rst.getString(4))*Integer.parseInt(db.rst.getString(5));
                tem.add(amt1+"");
                data.add(tem);
            }
            jTable3.setModel(new DefaultTableModel(data,head));

            db.pstmt=db.con.prepareStatement("select date,cust_name,cust_cont,bill_amt from bill_detail where invc_no=?");
            db.pstmt.setInt(1,invc);
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next()){
                jLabel62.setText(""+invc);
                jLabel63.setText(db.rst.getString(2));
                jLabel66.setText(db.rst.getString(1));
                jLabel67.setText(db.rst.getString(3));
                jLabel22.setText(db.rst.getString(4));
            }
            GnrtInvc.setVisible(false);
            Bill.setVisible(true);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jTextField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        if(jComboBox3.getSelectedItem()!=null){
        try{
            String mname=jComboBox3.getSelectedItem()+"";
            DBConnection db=new DBConnection();
            db.pstmt=db.con.prepareStatement("select med_sp,med_mfd, med_exd,med_qty from stock_detail where med_qty>0 and med_name=?");
            db.pstmt.setString(1,mname);
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next()){
                jTextField36.setText(db.rst.getString(1));
                jTextField37.setText(db.rst.getString(2));
                jTextField38.setText(db.rst.getString(3));
                jTextField39.setText(db.rst.getString(4));
                jTextField36.setEditable(false);
                jTextField37.setEditable(false);
                jTextField38.setEditable(false);
                jTextField39.setEditable(false);
            }
            else{
                JOptionPane.showMessageDialog(this,"Not in Stock");
                jTextField36.setText("");
                jTextField37.setText("");
                jTextField38.setText("");
                jTextField39.setText("");
                jTextField40.setText("");

            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            /*jTextField36.setText("");
            jTextField37.setText("");
            jTextField38.setText("");
            jTextField39.setText("");
            jTextField36.setText("");*/
           DBConnection db=new DBConnection();
           db.pstmt=db.con.prepareStatement("select med_name from stock_detail");
           db.rst=db.pstmt.executeQuery();
           jComboBox3.removeAllItems();
           while(db.rst.next()){
               jComboBox3.addItem(db.rst.getString(1));
           }
          // Gnt_Invc.setVisible(true
          GnrtInvc.setVisible(true);
           db.pstmt=db.con.prepareStatement("select MAX(invc_no) from bill_detail");
           db.rst=db.pstmt.executeQuery();
           if(db.rst.next()){
               invc=db.rst.getInt(1);
               invc++;
           }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        try{
           DBConnection db=new DBConnection();
           db.pstmt=db.con.prepareStatement("select med_name from product_mstr");
           db.rst=db.pstmt.executeQuery();
           jComboBox3.removeAllItems();
           while(db.rst.next()){
               jComboBox3.addItem(db.rst.getString(1));
           }
          // Gnt_Invc.setVisible(true
          GnrtInvc.setVisible(true);
           db.pstmt=db.con.prepareStatement("select MAX(invc_no) from bill_detail");
           db.rst=db.pstmt.executeQuery();
           if(db.rst.next()){
               invc=db.rst.getInt(1);
               invc++;
           }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            DBConnection db=new DBConnection();
            db.pstmt=db.con.prepareStatement("select * from emp_mstr where email=?");
            db.pstmt.setString(1,user);
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next()){
                jTextField1.setText(db.rst.getString(1));
                jTextField2.setText(db.rst.getString(2));
                jTextField3.setText(db.rst.getString(3));
                jTextField4.setText(db.rst.getString(4));
                jTextField5.setText(db.rst.getString(5));
                jTextField6.setText(db.rst.getString(6));
                jTextField7.setText(db.rst.getString(7));
                jTextField8.setText(db.rst.getString(8));
                jTextField9.setText(db.rst.getString(9));
            }
            profile.setVisible(true);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginWindow().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginWindow().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        chng_pass.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{
            String old_pass=jPasswordField1.getText();
            String new_pass=jPasswordField2.getText();
            String con_pass=jPasswordField3.getText();
             DBConnection db=new DBConnection();
            db.pstmt=db.con.prepareStatement("select * from emp_mstr where password=? and email=?");
            db.pstmt.setString(1,old_pass);
            db.pstmt.setString(2,user);
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next()){
                if(new_pass.equals(con_pass)){
                    db.pstmt=db.con.prepareStatement("update emp_mstr set password=? where email=?");
                    db.pstmt.setString(1,new_pass);
                    db.pstmt.setString(2,user);
                    int t=db.pstmt.executeUpdate();
                    if(t>0){
                        JOptionPane.showMessageDialog(this,"Password Updated Successfully");
                        chng_pass.setVisible(false);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"new password doesn't matches with confirm password");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"old password is incorrect");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        chng_pass.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        billSearch.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        billSearch.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         try{
            String bill=jTextField10.getText();
            DBConnection db=new DBConnection();
            db.pstmt=db.con.prepareStatement("select * from bill_detail where invc_no=?");
            db.pstmt.setString(1,bill);
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next()){
                billSearch.setVisible(false);
                view_bill.setVisible(true);
                
                //bill view 
                int amn=0,price,qnty;
                invc=Integer.parseInt(bill);
                db.pstmt=db.con.prepareStatement("select med_price , med_qty from invoice where invoice_id=?");
                db.pstmt.setInt(1,invc);
                db.rst=db.pstmt.executeQuery();
                while(db.rst.next()){
                    price=db.rst.getInt(1);
                    qnty=db.rst.getInt(2);
                    amn+=(price*qnty);
                }
              
                Vector<String> head=new Vector<String>();
                Vector<Vector<String>> data=new  Vector<Vector<String>>();
                head.add("Medicine name");
                head.add("Mfd. Date");
                head.add("Exp. Date");
                head.add("Price");
                head.add("Quantity");
                head.add("Amount");
                db.pstmt=db.con.prepareStatement("select invoice.med_name,stock_detail.med_mfd,stock_detail.med_exd,invoice.med_price,invoice.med_qty from invoice,stock_detail where invoice.med_name=stock_detail.med_name and invoice_id=?");
                db.pstmt.setInt(1,invc);
                db.rst=db.pstmt.executeQuery();
                while(db.rst.next()){
                    Vector<String> tem=new Vector<String>();
                    tem.add(db.rst.getString(1));
                    tem.add(db.rst.getString(2));
                    tem.add(db.rst.getString(3));
                    tem.add(db.rst.getString(4));
                    tem.add(db.rst.getString(5));
                    int amt1=Integer.parseInt(db.rst.getString(4))*Integer.parseInt(db.rst.getString(5));
                    tem.add(amt1+"");
                    data.add(tem);
                }
                jTable4.setModel(new DefaultTableModel(data,head));

                 db.pstmt=db.con.prepareStatement("select date,cust_name,cust_cont,bill_amt from bill_detail where invc_no=?");
                 db.pstmt.setInt(1,invc);
                 db.rst=db.pstmt.executeQuery();
                 if(db.rst.next()){
                     jLabel75.setText(""+invc);
                     jLabel76.setText(db.rst.getString(2));
                     jLabel79.setText(db.rst.getString(1));
                     jLabel80.setText(db.rst.getString(3));
                     jLabel20.setText(db.rst.getString(4));
                 }
            }
            else{
                JOptionPane.showMessageDialog(this,"bill number doesn't exist");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Bill;
    private javax.swing.JInternalFrame GnrtInvc;
    private javax.swing.JInternalFrame billSearch;
    private javax.swing.JInternalFrame chng_pass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JInternalFrame profile;
    private javax.swing.JInternalFrame view_bill;
    // End of variables declaration//GEN-END:variables
}
