/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package schoolmanagement;

import DB.DBConnection;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Snippy066
 */
public class StudentWindow extends javax.swing.JFrame {

    /**
     * Creates new form StudentWindow
     */
    public StudentWindow() {
        initComponents();
    }
  String user;
    public StudentWindow(String uname) {
        initComponents();
        user=uname;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        notiLis = new javax.swing.JInternalFrame();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jLabel52 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        srchNot = new javax.swing.JInternalFrame();
        jPanel8 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel54 = new javax.swing.JLabel();
        liNoti = new javax.swing.JInternalFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        changPass = new javax.swing.JInternalFrame();
        jPanel24 = new javax.swing.JPanel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jSeparator27 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel105 = new javax.swing.JLabel();
        stuReport = new javax.swing.JInternalFrame();
        jPanel18 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolProject/mess.png"))); // NOI18N
        jButton1.setToolTipText("View Notification");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolProject/memser.png"))); // NOI18N
        jButton2.setToolTipText("View notification");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolProject/id.png"))); // NOI18N
        jButton4.setToolTipText("View Report");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolProject/chng.png"))); // NOI18N
        jButton5.setToolTipText("Change Password");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolProject/logout.png"))); // NOI18N
        jButton6.setToolTipText("Log Out");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jDesktopPane1.setBackground(new java.awt.Color(204, 255, 204));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notiLis.setClosable(true);
        notiLis.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        notiLis.setTitle("All Notification List");
        notiLis.setVisible(false);

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable7);

        jPanel17.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1540, 530));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 44)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 0, 0));
        jLabel52.setText("Notification List");
        jPanel17.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));
        jPanel17.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 430, 20));

        javax.swing.GroupLayout notiLisLayout = new javax.swing.GroupLayout(notiLis.getContentPane());
        notiLis.getContentPane().setLayout(notiLisLayout);
        notiLisLayout.setHorizontalGroup(
            notiLisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 1544, Short.MAX_VALUE)
        );
        notiLisLayout.setVerticalGroup(
            notiLisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(notiLis, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 1560, 690));

        srchNot.setClosable(true);
        srchNot.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        srchNot.setTitle("Search Notification");
        srchNot.setVisible(false);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 44)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Search Notiification");
        jPanel8.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Search Notifications By ID :");
        jPanel8.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 30));

        jButton22.setBackground(new java.awt.Color(255, 255, 255));
        jButton22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton22.setForeground(new java.awt.Color(51, 255, 0));
        jButton22.setText("Search");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, 40));
        jPanel8.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 520, 20));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 176, 600, 40));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolProject/gra.jpg"))); // NOI18N
        jPanel8.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 420));

        javax.swing.GroupLayout srchNotLayout = new javax.swing.GroupLayout(srchNot.getContentPane());
        srchNot.getContentPane().setLayout(srchNotLayout);
        srchNotLayout.setHorizontalGroup(
            srchNotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        srchNotLayout.setVerticalGroup(
            srchNotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(srchNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 1180, 460));

        liNoti.setClosable(true);
        liNoti.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        liNoti.setVisible(false);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 0, 51));
        jLabel55.setText("Notifications");
        jPanel9.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));
        jPanel9.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 320, 20));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 1480, 550));

        javax.swing.GroupLayout liNotiLayout = new javax.swing.GroupLayout(liNoti.getContentPane());
        liNoti.getContentPane().setLayout(liNotiLayout);
        liNotiLayout.setHorizontalGroup(
            liNotiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 1484, Short.MAX_VALUE)
        );
        liNotiLayout.setVerticalGroup(
            liNotiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );

        jDesktopPane1.add(liNoti, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 1500, 690));

        changPass.setClosable(true);
        changPass.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        changPass.setTitle("Change Password");
        changPass.setVisible(false);

        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel106.setFont(new java.awt.Font("Tahoma", 1, 46)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(255, 255, 255));
        jLabel106.setText("Change Password");
        jPanel24.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel107.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(255, 255, 255));
        jLabel107.setText("Old Password :");
        jPanel24.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel108.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(255, 255, 255));
        jLabel108.setText("New Password :");
        jPanel24.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel109.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(255, 255, 255));
        jLabel109.setText("Confirm Password :");
        jPanel24.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jButton41.setForeground(new java.awt.Color(0, 0, 153));
        jButton41.setText("Reset");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jPanel24.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 439, 110, 40));

        jButton42.setForeground(new java.awt.Color(255, 153, 0));
        jButton42.setText("Update");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        jPanel24.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 439, 110, 40));
        jPanel24.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 480, 40));
        jPanel24.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 136, 370, 40));

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel24.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 236, 370, 40));
        jPanel24.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 336, 370, 40));

        jLabel105.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(255, 255, 255));
        jLabel105.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolProject/lock.jpg"))); // NOI18N
        jPanel24.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout changPassLayout = new javax.swing.GroupLayout(changPass.getContentPane());
        changPass.getContentPane().setLayout(changPassLayout);
        changPassLayout.setHorizontalGroup(
            changPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        changPassLayout.setVerticalGroup(
            changPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(changPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 920, -1));

        stuReport.setClosable(true);
        stuReport.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        stuReport.setTitle("Report");
        stuReport.setVisible(false);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 44)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(204, 0, 0));
        jLabel56.setText("Student Report");
        jPanel18.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));
        jPanel18.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 460, 40));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel57.setText("Student ID :");
        jPanel18.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel58.setText("Name :");
        jPanel18.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel59.setText("Department :");
        jPanel18.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel60.setText("Course :");
        jPanel18.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel61.setText("Address :");
        jPanel18.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, -1));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel62.setText("E-mail :");
        jPanel18.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel63.setText("Mobile :");
        jPanel18.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, -1, -1));

        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField19.setText("jTextField19");
        jPanel18.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 390, 40));

        jTextField20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField20.setText("jTextField20");
        jPanel18.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 390, 40));

        jTextField21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField21.setText("jTextField21");
        jPanel18.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 390, 40));

        jTextField22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField22.setText("jTextField22");
        jPanel18.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 390, 40));

        jTextField23.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField23.setText("jTextField23");
        jPanel18.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 390, 40));

        jTextField24.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField24.setText("jTextField24");
        jPanel18.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 390, 40));

        jTextField25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField25.setText("jTextField25");
        jPanel18.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 390, 40));

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel64.setText("Father's name :");
        jPanel18.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, -1, -1));

        jTextField27.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField27.setText("jTextField27");
        jPanel18.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 400, 40));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel65.setText("Total Attandance :");
        jPanel18.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 470, 160, 30));

        jTextField28.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField28.setText("jTextField28");
        jPanel18.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, 400, 40));

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel71.setText("Total absent :");
        jPanel18.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, -1, 30));

        jTextField29.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField29.setText("jTextField29");
        jPanel18.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 570, 400, 40));

        javax.swing.GroupLayout stuReportLayout = new javax.swing.GroupLayout(stuReport.getContentPane());
        stuReport.getContentPane().setLayout(stuReportLayout);
        stuReportLayout.setHorizontalGroup(
            stuReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 1314, Short.MAX_VALUE)
        );
        stuReportLayout.setVerticalGroup(
            stuReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        jDesktopPane1.add(stuReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 1330, 680));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolProject/animeres.png"))); // NOI18N
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 1760, 750));

        jMenu1.setText("Notification ");

        jMenuItem1.setText("View Notification");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Search Notification");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("View Report");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("View Report");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Account");

        jMenuItem3.setText("Change Password");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Sign Out");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1905, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try{
            Vector<String> head=new Vector<String>();
            Vector<Vector<String>> data=new Vector<Vector<String>>();
            head.add("Notification Id");
            head.add("Notifications");
            head.add("Data");
            DBConnection db=new DBConnection();
            db.pstmt=db.con.prepareStatement("select * from notfications");
            db.rst=db.pstmt.executeQuery();
            while(db.rst.next()){
                Vector<String> temp=new Vector<String>();
                temp.add(db.rst.getString(1));
                temp.add(db.rst.getString(2));
                temp.add(db.rst.getString(3));
                data.add(temp);
            }
            jTable7.setModel(new DefaultTableModel(data,head));
            notiLis.setVisible(true);
        }
        catch(Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        if(jComboBox4.getSelectedItem()!=null){
            try{
                String id=jComboBox4.getSelectedItem().toString();
                DBConnection db= new DBConnection();
                db.pstmt=db.con.prepareStatement("select * from notfications where notiId=?");
                db.pstmt.setString(1,id);
                db.rst=db.pstmt.executeQuery();
                if(db.rst.next()){
                    jTextArea2.setText(db.rst.getString(2));
                }
                liNoti.setVisible(true);
                srchNot.setVisible(false);
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Vector<String> head=new Vector<String>();
            Vector<Vector<String>> data=new Vector<Vector<String>>();
            head.add("Notification Id");
            head.add("Notifications");
            head.add("Data");
            DBConnection db=new DBConnection();
            db.pstmt=db.con.prepareStatement("select * from notfications");
            db.rst=db.pstmt.executeQuery();
            while(db.rst.next()){
                Vector<String> temp=new Vector<String>();
                temp.add(db.rst.getString(1));
                temp.add(db.rst.getString(2));
                temp.add(db.rst.getString(3));
                data.add(temp);
            }
            jTable7.setModel(new DefaultTableModel(data,head));
            notiLis.setVisible(true);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try{
            DBConnection db=new DBConnection();
            db.pstmt=db.con.prepareStatement("select notiId from notfications");
            db.rst=db.pstmt.executeQuery();
            jComboBox4.removeAllItems();
            while(db.rst.next()){
                jComboBox4.addItem(db.rst.getString(1));
            }
            srchNot.setVisible(true);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
            DBConnection db=new DBConnection();
            db.pstmt=db.con.prepareStatement("select notiId from notfications");
            db.rst=db.pstmt.executeQuery();
            jComboBox4.removeAllItems();
            while(db.rst.next()){
                jComboBox4.addItem(db.rst.getString(1));
            }
            srchNot.setVisible(true);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        jPasswordField3.setText("");
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        // TODO add your handling code here:
        try{
            String old=jPasswordField1.getText();
            String newpass=jPasswordField2.getText();
            String coonpas=jPasswordField3.getText();
            DBConnection db =new DBConnection();
            db.pstmt=db.con.prepareStatement("select * from adstudent where stmail=?");
            db.pstmt.setString(1,user);
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next()){
                String pass=db.rst.getString(9);
                if(old.equals(pass)){
                    if(newpass.equals(coonpas)){
                        db.pstmt=db.con.prepareStatement("update adstudent set stpass=? where stmail=?");
                        db.pstmt.setString(1,newpass);
                        db.pstmt.setString(2,user);
                        int i=db.pstmt.executeUpdate();
                        if(i>0){
                            JOptionPane.showMessageDialog(this,"Password updated successfully");
                            changPass.setVisible(false);
                        }
                        else{
                            JOptionPane.showMessageDialog(this,"Error in updation");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"new and comfirm password doesn't matches");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"Incorrect Old Password");
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        changPass.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        changPass.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginWindow().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginWindow().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        try{
            String id="";
            DBConnection db=new DBConnection();
            db.pstmt=db.con.prepareStatement("select * from adstudent where stmail=?");
            db.pstmt.setString(1, user);
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next()){
                id=db.rst.getString(1);
                jTextField19.setText(db.rst.getString(1));
                jTextField20.setText(db.rst.getString(2));
                jTextField21.setText(db.rst.getString(3));
                jTextField22.setText(db.rst.getString(4));
                jTextField23.setText(db.rst.getString(10));
                jTextField24.setText(db.rst.getString(8));
                jTextField25.setText(db.rst.getString(6));
                jTextField27.setText(db.rst.getString(5));
            }
            
            db.pstmt=db.con.prepareStatement("select count(stid) from attend where stid=? ");
            db.pstmt.setString(1,id);
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next()){
                jTextField28.setText(db.rst.getString(1));
                
            }
            db.pstmt=db.con.prepareStatement("select count(stid) from attend where stid=? && atnd='a'");
            db.pstmt.setString(1,id);
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next()){
                jTextField29.setText(db.rst.getString(1));
                
            }
            stuReport.setVisible(true);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame changPass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JInternalFrame liNoti;
    private javax.swing.JInternalFrame notiLis;
    private javax.swing.JInternalFrame srchNot;
    private javax.swing.JInternalFrame stuReport;
    // End of variables declaration//GEN-END:variables
}
